2023-03-07 21:52:57,158 INFO    MainThread:134368 [internal.py:wandb_internal():90] W&B internal server running at pid: 134368, started at: 2023-03-07 21:52:57.157045
2023-03-07 21:52:57,160 INFO    WriterThread:134368 [datastore.py:open_for_write():75] open: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\run-ynqj7ir8.wandb
2023-03-07 21:52:57,164 DEBUG   SenderThread:134368 [sender.py:send():232] send: header
2023-03-07 21:52:57,164 DEBUG   SenderThread:134368 [sender.py:send():232] send: run
2023-03-07 21:52:57,172 INFO    SenderThread:134368 [sender.py:_maybe_setup_resume():489] checking resume status for None/train/ynqj7ir8
2023-03-07 21:52:59,226 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: check_version
2023-03-07 21:52:59,236 INFO    SenderThread:134368 [dir_watcher.py:__init__():197] watching files in: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files
2023-03-07 21:52:59,236 INFO    SenderThread:134368 [sender.py:_start_run_threads():811] run started: ynqj7ir8 with start time 1678197175
2023-03-07 21:52:59,236 DEBUG   SenderThread:134368 [sender.py:send():232] send: summary
2023-03-07 21:52:59,237 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file wandb-summary.json with policy end
2023-03-07 21:52:59,237 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: check_version
2023-03-07 21:52:59,980 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: run_start
2023-03-07 21:53:00,001 DEBUG   HandlerThread:134368 [meta.py:__init__():35] meta init
2023-03-07 21:53:00,001 DEBUG   HandlerThread:134368 [meta.py:__init__():49] meta init done
2023-03-07 21:53:00,001 DEBUG   HandlerThread:134368 [meta.py:probe():209] probe
2023-03-07 21:53:00,008 DEBUG   HandlerThread:134368 [meta.py:_save_pip():53] save pip
2023-03-07 21:53:00,009 DEBUG   HandlerThread:134368 [meta.py:_save_pip():67] save pip done
2023-03-07 21:53:00,009 DEBUG   HandlerThread:134368 [meta.py:_save_conda():74] save conda
2023-03-07 21:53:00,244 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_created():244] file/dir created: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\requirements.txt
2023-03-07 21:53:00,244 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_created():244] file/dir created: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\conda-environment.yaml
2023-03-07 21:53:00,244 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_created():244] file/dir created: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\wandb-summary.json
2023-03-07 21:53:05,274 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_created():244] file/dir created: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:53:06,673 DEBUG   HandlerThread:134368 [meta.py:_save_conda():84] save conda done
2023-03-07 21:53:06,673 DEBUG   HandlerThread:134368 [meta.py:probe():247] probe done
2023-03-07 21:53:06,794 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:53:06,795 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:53:07,291 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\conda-environment.yaml
2023-03-07 21:53:07,291 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:53:07,292 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_created():244] file/dir created: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\wandb-metadata.json
2023-03-07 21:53:07,797 DEBUG   SenderThread:134368 [sender.py:send():232] send: telemetry
2023-03-07 21:53:07,798 DEBUG   SenderThread:134368 [sender.py:send():232] send: config
2023-03-07 21:53:07,798 DEBUG   SenderThread:134368 [sender.py:send():232] send: files
2023-03-07 21:53:07,798 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file wandb-metadata.json with policy now
2023-03-07 21:53:10,325 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221B7F70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:53:10,325 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '529'}
2023-03-07 21:53:10,325 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:53:11,317 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:53:13,558 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221C70A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:53:13,558 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '529'}
2023-03-07 21:53:13,558 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:53:15,343 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:53:17,658 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221D1070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:53:17,663 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '529'}
2023-03-07 21:53:17,663 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:53:17,663 ERROR   Thread-11 :134368 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000265221D1070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221D1070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221D1070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1653, in upload_file
    raise e.with_traceback(sys.exc_info()[2])
  File "E:\anaconda3\envs\zhangxin\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-03-07 21:53:22,799 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:53:22,800 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:53:24,564 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221D1E50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:53:24,565 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '529'}
2023-03-07 21:53:24,565 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:53:28,441 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\config.yaml
2023-03-07 21:53:30,954 DEBUG   SenderThread:134368 [sender.py:send():232] send: stats
2023-03-07 21:53:35,345 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221B7820>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:53:35,345 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '529'}
2023-03-07 21:53:35,346 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:53:38,256 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:53:38,257 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:53:53,711 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:53:53,711 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:53:55,318 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221D14F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:53:55,318 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '529'}
2023-03-07 21:53:55,319 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:54:03,701 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:54:04,277 DEBUG   SenderThread:134368 [sender.py:send():232] send: stats
2023-03-07 21:54:09,175 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:54:09,176 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:54:24,603 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:54:24,604 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:54:29,982 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002652206F190>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:54:29,983 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '529'}
2023-03-07 21:54:29,983 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:54:37,532 DEBUG   SenderThread:134368 [sender.py:send():232] send: stats
2023-03-07 21:54:40,035 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:54:40,036 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:54:55,483 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:54:55,484 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:55:10,811 DEBUG   SenderThread:134368 [sender.py:send():232] send: stats
2023-03-07 21:55:10,922 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:55:10,923 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:55:26,500 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:55:26,500 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:55:34,409 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:55:38,449 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:55:40,461 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:55:42,110 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:55:42,110 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:55:42,474 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:55:44,047 DEBUG   SenderThread:134368 [sender.py:send():232] send: stats
2023-03-07 21:55:44,496 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:55:46,508 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:55:48,523 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:55:49,063 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/wandb-metadata.json?Expires=1678283588&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vx%2BEjqY7OtbKSf6pH9jXp7ZQbdRDKw1Yu2gXHUkcMIQx51XGbgZDd1bX4Q1ryP19zxeD%2FbIsgZIszeUkVRJwIslGMJpihKHmx4jU0mX%2FlqQNfMfPvsqRfstCs5I5yLveG%2FQpZ9FPCA1T2w6HwSq1rCYLQz6yWk0MmCl4HVMURZF8FWACKTAp%2F3S1erpRFAzNgUi0zciVtUeObsJMo%2BF9B5Tdx0PFX7GMp01BSbcZB0uhr6S8m99kGUQxraMAOCOUgfKgBDKeMK1cgSePEdatnBNo%2B1IbB5q488j00%2F8Cj%2FVaquq0HuiERogOYpl1Tq%2FOnQ0sOGSpTJXPvTIwAyCk6A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026521FAF9D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:55:49,063 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '529'}
2023-03-07 21:55:49,063 ERROR   Thread-11 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:55:50,539 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:55:52,551 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:55:54,566 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:55:56,577 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:55:57,581 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:55:57,582 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:55:58,588 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:00,596 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:02,612 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:04,621 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:06,637 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:08,648 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:10,659 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:12,673 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:13,042 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:56:13,043 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:56:14,680 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:16,697 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:17,073 DEBUG   SenderThread:134368 [sender.py:send():232] send: stats
2023-03-07 21:56:18,721 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:20,731 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:22,751 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:24,767 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:26,788 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:28,543 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:56:28,544 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:56:28,807 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:30,827 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:32,835 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:34,845 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:36,861 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:38,877 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:40,891 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:42,905 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:44,020 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:56:44,020 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:56:44,918 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:46,928 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:48,950 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:50,194 DEBUG   SenderThread:134368 [sender.py:send():232] send: stats
2023-03-07 21:56:50,961 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:52,973 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:54,991 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:57,001 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:59,028 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:56:59,414 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:56:59,415 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:57:01,042 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:03,057 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:05,068 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:07,080 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:09,096 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:11,109 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:13,122 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:14,919 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:57:14,920 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:57:15,138 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:17,150 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:19,170 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:20,472 DEBUG   SenderThread:134368 [sender.py:send():232] send: summary
2023-03-07 21:57:20,474 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file wandb-summary.json with policy end
2023-03-07 21:57:20,474 DEBUG   SenderThread:134368 [sender.py:send():232] send: summary
2023-03-07 21:57:20,476 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file wandb-summary.json with policy end
2023-03-07 21:57:20,476 DEBUG   SenderThread:134368 [sender.py:send():232] send: summary
2023-03-07 21:57:20,478 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file wandb-summary.json with policy end
2023-03-07 21:57:20,478 DEBUG   SenderThread:134368 [sender.py:send():232] send: summary
2023-03-07 21:57:20,479 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file wandb-summary.json with policy end
2023-03-07 21:57:20,480 DEBUG   SenderThread:134368 [sender.py:send():232] send: summary
2023-03-07 21:57:20,481 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file wandb-summary.json with policy end
2023-03-07 21:57:21,192 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:21,193 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\wandb-summary.json
2023-03-07 21:57:21,380 DEBUG   SenderThread:134368 [sender.py:send():232] send: files
2023-03-07 21:57:21,380 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file media\images\Labels_0_ddb4b29c59b20d5c56a4.jpg with policy now
2023-03-07 21:57:21,389 DEBUG   SenderThread:134368 [sender.py:send():232] send: files
2023-03-07 21:57:21,389 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file media\images\Labels_0_a09086ac7fbb3b332fc5.jpg with policy now
2023-03-07 21:57:21,462 DEBUG   SenderThread:134368 [sender.py:send():232] send: files
2023-03-07 21:57:21,462 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file media\images\Mosaics_0_c2b39e1ae8e38500e36b.jpg with policy now
2023-03-07 21:57:21,475 DEBUG   SenderThread:134368 [sender.py:send():232] send: files
2023-03-07 21:57:21,476 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file media\images\Mosaics_0_30d3bf9e21f9f1d09aa9.jpg with policy now
2023-03-07 21:57:21,487 DEBUG   SenderThread:134368 [sender.py:send():232] send: files
2023-03-07 21:57:21,487 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file media\images\Mosaics_0_89e164201c08ac4003fe.jpg with policy now
2023-03-07 21:57:21,599 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: partial_history
2023-03-07 21:57:21,601 DEBUG   SenderThread:134368 [sender.py:send():232] send: history
2023-03-07 21:57:21,602 DEBUG   SenderThread:134368 [sender.py:send():232] send: summary
2023-03-07 21:57:21,605 INFO    SenderThread:134368 [sender.py:_save_file():948] saving file wandb-summary.json with policy end
2023-03-07 21:57:22,200 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\wandb-summary.json
2023-03-07 21:57:22,201 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_created():244] file/dir created: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\media\images\Mosaics_0_c2b39e1ae8e38500e36b.jpg
2023-03-07 21:57:22,202 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_created():244] file/dir created: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\media\images\Mosaics_0_30d3bf9e21f9f1d09aa9.jpg
2023-03-07 21:57:22,202 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_created():244] file/dir created: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\media\images\Mosaics_0_89e164201c08ac4003fe.jpg
2023-03-07 21:57:22,203 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_created():244] file/dir created: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\media\images\Labels_0_ddb4b29c59b20d5c56a4.jpg
2023-03-07 21:57:22,204 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_created():244] file/dir created: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\media\images\Labels_0_a09086ac7fbb3b332fc5.jpg
2023-03-07 21:57:22,204 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_created():244] file/dir created: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\media\images
2023-03-07 21:57:22,205 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_created():244] file/dir created: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\media
2023-03-07 21:57:23,202 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:23,365 DEBUG   SenderThread:134368 [sender.py:send():232] send: stats
2023-03-07 21:57:23,910 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_a09086ac7fbb3b332fc5.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=cn4m2CZwktpYHxFd8vaH64FCjFj9f8SnXNIgPhJkd1U1SLehyHEODS1n1%2FQwElgIahD0Ta1HXMBYTWkZtlmDDx%2BtiWflWF5TcBFZcKqBVhjlsoJk0Pd%2FUba%2B4ZGR05i%2F8C9kt8lHKkOA1qzpPml2C84%2BbXoaotjfLUqQ7KYanOl5kH9PfdESgAx9wj7uTKEMOvUk5tunlqignVUeiBKE5go%2FykRgXqUTBiB%2FkKKuVIc66D2wFgtdks71OgKnWLHq%2BDIQC7ZqNbSCejro1jijbd64%2F9RQ%2BJQcfQ%2FWSifMz5rrLleyRKqYnFjAk1myjxTpxuazFcxMfxkDFultPDdqSw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_a09086ac7fbb3b332fc5.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=cn4m2CZwktpYHxFd8vaH64FCjFj9f8SnXNIgPhJkd1U1SLehyHEODS1n1%2FQwElgIahD0Ta1HXMBYTWkZtlmDDx%2BtiWflWF5TcBFZcKqBVhjlsoJk0Pd%2FUba%2B4ZGR05i%2F8C9kt8lHKkOA1qzpPml2C84%2BbXoaotjfLUqQ7KYanOl5kH9PfdESgAx9wj7uTKEMOvUk5tunlqignVUeiBKE5go%2FykRgXqUTBiB%2FkKKuVIc66D2wFgtdks71OgKnWLHq%2BDIQC7ZqNbSCejro1jijbd64%2F9RQ%2BJQcfQ%2FWSifMz5rrLleyRKqYnFjAk1myjxTpxuazFcxMfxkDFultPDdqSw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221B7130>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:23,910 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '256560'}
2023-03-07 21:57:23,910 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:23,940 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_ddb4b29c59b20d5c56a4.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Up74wXhlcgvelQjsvpQFEjXfNTGP%2FvrWWSrPsI8BSJ8i%2B2rjxtVhGEGEzLZ1DRKgPQEWy5DgXyQ8uopRdIUqd0s4Pi3ReQmvzPHHu3eE53aFalAmguRq6TslVsa7ztEFmPtw4xDCqiUbKyApRsjXp013rzsedhk0PDFNGeKCnrS%2FQGSH9tEwFjgbyXKxp5ClR8Ql%2FnxZYidfKisX%2Bx4kDpy60OJWFO2Yrl298DWNG%2B4pLvef%2FMWfg1RAa4%2BJNaRrciljlgdz0hf3PhL%2B8%2Fp5YX5Y8nAWqtFYONbAa8XrzgWlMbpCDwmc97AodPc2qutaN0RyOv0OZBNucO5VlfbX9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_ddb4b29c59b20d5c56a4.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Up74wXhlcgvelQjsvpQFEjXfNTGP%2FvrWWSrPsI8BSJ8i%2B2rjxtVhGEGEzLZ1DRKgPQEWy5DgXyQ8uopRdIUqd0s4Pi3ReQmvzPHHu3eE53aFalAmguRq6TslVsa7ztEFmPtw4xDCqiUbKyApRsjXp013rzsedhk0PDFNGeKCnrS%2FQGSH9tEwFjgbyXKxp5ClR8Ql%2FnxZYidfKisX%2Bx4kDpy60OJWFO2Yrl298DWNG%2B4pLvef%2FMWfg1RAa4%2BJNaRrciljlgdz0hf3PhL%2B8%2Fp5YX5Y8nAWqtFYONbAa8XrzgWlMbpCDwmc97AodPc2qutaN0RyOv0OZBNucO5VlfbX9Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221C7E50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:23,941 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '241359'}
2023-03-07 21:57:23,941 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:24,049 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_89e164201c08ac4003fe.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=j9RzS69C8Nqxh8nnyowQW%2F6rZ7Pw03gvQKydvawmeKhqZq7Bv23Dry6nbDd3rgyNBIrha4huYwIllRuIIdxlyOPSCD8qY11lOlyCPDSE%2BG0umKLFWeTxD0cNBosYeECRRtVgjyf13HSMNePPcuKm2HJRT9PlIO3WyxtH%2Fmn9M0yLviqZnR0VhN81UjnL14oq%2BSycvvWdJv7JbD%2Fv45%2BubHjV7p%2BbqkAxbdyAiW6OlPVK9wgxsDDGoQ2sroRMjPtdRKTlVH4SudL6ASM1hIgjqCoKbvSFOMmEcyx%2FKMcnNl%2BXt2TM8n%2BPhd7WYZbkiDcMl0CB6DUelXKLUHDw4mqVPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_89e164201c08ac4003fe.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=j9RzS69C8Nqxh8nnyowQW%2F6rZ7Pw03gvQKydvawmeKhqZq7Bv23Dry6nbDd3rgyNBIrha4huYwIllRuIIdxlyOPSCD8qY11lOlyCPDSE%2BG0umKLFWeTxD0cNBosYeECRRtVgjyf13HSMNePPcuKm2HJRT9PlIO3WyxtH%2Fmn9M0yLviqZnR0VhN81UjnL14oq%2BSycvvWdJv7JbD%2Fv45%2BubHjV7p%2BbqkAxbdyAiW6OlPVK9wgxsDDGoQ2sroRMjPtdRKTlVH4SudL6ASM1hIgjqCoKbvSFOMmEcyx%2FKMcnNl%2BXt2TM8n%2BPhd7WYZbkiDcMl0CB6DUelXKLUHDw4mqVPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026522280FA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:24,050 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_c2b39e1ae8e38500e36b.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=T%2BFpHhktsAz7E%2B94jlB6IPrCOhYGwe1Xcy0HmJz6SxzeVqatVGyoZ6ZMPd2lxUFduVZpiMXz5qC9GgF71dsIIjhLidhUb2M7TD3XZw2qDHGuNWx6D23gWlxU1uU8XWdcjk2bCHkyCnDjd7Ais7ENsAcgzus90YO%2BBtpgnEXsRWWTL9Uv84LcwJGbrBMPTQkpD42tQBfNjXMQCX%2B5M7nVcIoenmnN%2B8oRCFYK21X3wuc5X6K5sn59mqRzCLFy7nlTxAHOKG9fxjdPcvouSa1MtDJAk3Ue209JEkz353r3DTteOS7jwq9OzHJuGDu0F8%2Fbl0bhrTF%2BQ1%2F4YBuIp0gCLg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_c2b39e1ae8e38500e36b.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=T%2BFpHhktsAz7E%2B94jlB6IPrCOhYGwe1Xcy0HmJz6SxzeVqatVGyoZ6ZMPd2lxUFduVZpiMXz5qC9GgF71dsIIjhLidhUb2M7TD3XZw2qDHGuNWx6D23gWlxU1uU8XWdcjk2bCHkyCnDjd7Ais7ENsAcgzus90YO%2BBtpgnEXsRWWTL9Uv84LcwJGbrBMPTQkpD42tQBfNjXMQCX%2B5M7nVcIoenmnN%2B8oRCFYK21X3wuc5X6K5sn59mqRzCLFy7nlTxAHOKG9fxjdPcvouSa1MtDJAk3Ue209JEkz353r3DTteOS7jwq9OzHJuGDu0F8%2Fbl0bhrTF%2BQ1%2F4YBuIp0gCLg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002652226A1C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:24,050 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '545229'}
2023-03-07 21:57:24,050 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '629870'}
2023-03-07 21:57:24,050 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:24,050 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:24,080 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_30d3bf9e21f9f1d09aa9.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=VJND22QekedbiBj5WE5sUcxNXECadZ30CHGFDUV%2B1JzZmDBuIq4msci5xhLYjV2ZXx0yzr8lK20wfLTZx6gF%2Bck9tqKpsSo2c1ExfTzyYfrCBB9a1%2BB9INad0V%2BzSFkUfmrjHV%2BEEPnDoffs%2F6DS9hcaTjb76BGbLoXX5q3qY5o9j%2FwtjhQb1npqCHvNOF%2FGUu%2FEeEFlFQNtolaOVT3cBZFwdD5LPr9wQ1fXXo%2BWclo9gs43hguWGOzl2FWVTCgEwRMmiiAkayLCPWFYGHJsllpS%2F0a0ZiI%2Fx7Boz6ehGNK2wJxvGMckaXRGYRl6wPTK1415TOfyLeBOAIW45Yzzmg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_30d3bf9e21f9f1d09aa9.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=VJND22QekedbiBj5WE5sUcxNXECadZ30CHGFDUV%2B1JzZmDBuIq4msci5xhLYjV2ZXx0yzr8lK20wfLTZx6gF%2Bck9tqKpsSo2c1ExfTzyYfrCBB9a1%2BB9INad0V%2BzSFkUfmrjHV%2BEEPnDoffs%2F6DS9hcaTjb76BGbLoXX5q3qY5o9j%2FwtjhQb1npqCHvNOF%2FGUu%2FEeEFlFQNtolaOVT3cBZFwdD5LPr9wQ1fXXo%2BWclo9gs43hguWGOzl2FWVTCgEwRMmiiAkayLCPWFYGHJsllpS%2F0a0ZiI%2Fx7Boz6ehGNK2wJxvGMckaXRGYRl6wPTK1415TOfyLeBOAIW45Yzzmg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002652226A5B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:24,080 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '630484'}
2023-03-07 21:57:24,080 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:25,222 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:26,998 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_ddb4b29c59b20d5c56a4.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Up74wXhlcgvelQjsvpQFEjXfNTGP%2FvrWWSrPsI8BSJ8i%2B2rjxtVhGEGEzLZ1DRKgPQEWy5DgXyQ8uopRdIUqd0s4Pi3ReQmvzPHHu3eE53aFalAmguRq6TslVsa7ztEFmPtw4xDCqiUbKyApRsjXp013rzsedhk0PDFNGeKCnrS%2FQGSH9tEwFjgbyXKxp5ClR8Ql%2FnxZYidfKisX%2Bx4kDpy60OJWFO2Yrl298DWNG%2B4pLvef%2FMWfg1RAa4%2BJNaRrciljlgdz0hf3PhL%2B8%2Fp5YX5Y8nAWqtFYONbAa8XrzgWlMbpCDwmc97AodPc2qutaN0RyOv0OZBNucO5VlfbX9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_ddb4b29c59b20d5c56a4.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Up74wXhlcgvelQjsvpQFEjXfNTGP%2FvrWWSrPsI8BSJ8i%2B2rjxtVhGEGEzLZ1DRKgPQEWy5DgXyQ8uopRdIUqd0s4Pi3ReQmvzPHHu3eE53aFalAmguRq6TslVsa7ztEFmPtw4xDCqiUbKyApRsjXp013rzsedhk0PDFNGeKCnrS%2FQGSH9tEwFjgbyXKxp5ClR8Ql%2FnxZYidfKisX%2Bx4kDpy60OJWFO2Yrl298DWNG%2B4pLvef%2FMWfg1RAa4%2BJNaRrciljlgdz0hf3PhL%2B8%2Fp5YX5Y8nAWqtFYONbAa8XrzgWlMbpCDwmc97AodPc2qutaN0RyOv0OZBNucO5VlfbX9Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026522270B80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:26,998 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '241359'}
2023-03-07 21:57:26,998 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:27,155 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_a09086ac7fbb3b332fc5.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=cn4m2CZwktpYHxFd8vaH64FCjFj9f8SnXNIgPhJkd1U1SLehyHEODS1n1%2FQwElgIahD0Ta1HXMBYTWkZtlmDDx%2BtiWflWF5TcBFZcKqBVhjlsoJk0Pd%2FUba%2B4ZGR05i%2F8C9kt8lHKkOA1qzpPml2C84%2BbXoaotjfLUqQ7KYanOl5kH9PfdESgAx9wj7uTKEMOvUk5tunlqignVUeiBKE5go%2FykRgXqUTBiB%2FkKKuVIc66D2wFgtdks71OgKnWLHq%2BDIQC7ZqNbSCejro1jijbd64%2F9RQ%2BJQcfQ%2FWSifMz5rrLleyRKqYnFjAk1myjxTpxuazFcxMfxkDFultPDdqSw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_a09086ac7fbb3b332fc5.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=cn4m2CZwktpYHxFd8vaH64FCjFj9f8SnXNIgPhJkd1U1SLehyHEODS1n1%2FQwElgIahD0Ta1HXMBYTWkZtlmDDx%2BtiWflWF5TcBFZcKqBVhjlsoJk0Pd%2FUba%2B4ZGR05i%2F8C9kt8lHKkOA1qzpPml2C84%2BbXoaotjfLUqQ7KYanOl5kH9PfdESgAx9wj7uTKEMOvUk5tunlqignVUeiBKE5go%2FykRgXqUTBiB%2FkKKuVIc66D2wFgtdks71OgKnWLHq%2BDIQC7ZqNbSCejro1jijbd64%2F9RQ%2BJQcfQ%2FWSifMz5rrLleyRKqYnFjAk1myjxTpxuazFcxMfxkDFultPDdqSw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026522286850>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:27,155 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '256560'}
2023-03-07 21:57:27,155 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:27,231 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_89e164201c08ac4003fe.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=j9RzS69C8Nqxh8nnyowQW%2F6rZ7Pw03gvQKydvawmeKhqZq7Bv23Dry6nbDd3rgyNBIrha4huYwIllRuIIdxlyOPSCD8qY11lOlyCPDSE%2BG0umKLFWeTxD0cNBosYeECRRtVgjyf13HSMNePPcuKm2HJRT9PlIO3WyxtH%2Fmn9M0yLviqZnR0VhN81UjnL14oq%2BSycvvWdJv7JbD%2Fv45%2BubHjV7p%2BbqkAxbdyAiW6OlPVK9wgxsDDGoQ2sroRMjPtdRKTlVH4SudL6ASM1hIgjqCoKbvSFOMmEcyx%2FKMcnNl%2BXt2TM8n%2BPhd7WYZbkiDcMl0CB6DUelXKLUHDw4mqVPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_89e164201c08ac4003fe.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=j9RzS69C8Nqxh8nnyowQW%2F6rZ7Pw03gvQKydvawmeKhqZq7Bv23Dry6nbDd3rgyNBIrha4huYwIllRuIIdxlyOPSCD8qY11lOlyCPDSE%2BG0umKLFWeTxD0cNBosYeECRRtVgjyf13HSMNePPcuKm2HJRT9PlIO3WyxtH%2Fmn9M0yLviqZnR0VhN81UjnL14oq%2BSycvvWdJv7JbD%2Fv45%2BubHjV7p%2BbqkAxbdyAiW6OlPVK9wgxsDDGoQ2sroRMjPtdRKTlVH4SudL6ASM1hIgjqCoKbvSFOMmEcyx%2FKMcnNl%2BXt2TM8n%2BPhd7WYZbkiDcMl0CB6DUelXKLUHDw4mqVPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221C7280>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:27,231 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '545229'}
2023-03-07 21:57:27,232 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:27,234 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:27,292 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_c2b39e1ae8e38500e36b.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=T%2BFpHhktsAz7E%2B94jlB6IPrCOhYGwe1Xcy0HmJz6SxzeVqatVGyoZ6ZMPd2lxUFduVZpiMXz5qC9GgF71dsIIjhLidhUb2M7TD3XZw2qDHGuNWx6D23gWlxU1uU8XWdcjk2bCHkyCnDjd7Ais7ENsAcgzus90YO%2BBtpgnEXsRWWTL9Uv84LcwJGbrBMPTQkpD42tQBfNjXMQCX%2B5M7nVcIoenmnN%2B8oRCFYK21X3wuc5X6K5sn59mqRzCLFy7nlTxAHOKG9fxjdPcvouSa1MtDJAk3Ue209JEkz353r3DTteOS7jwq9OzHJuGDu0F8%2Fbl0bhrTF%2BQ1%2F4YBuIp0gCLg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_c2b39e1ae8e38500e36b.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=T%2BFpHhktsAz7E%2B94jlB6IPrCOhYGwe1Xcy0HmJz6SxzeVqatVGyoZ6ZMPd2lxUFduVZpiMXz5qC9GgF71dsIIjhLidhUb2M7TD3XZw2qDHGuNWx6D23gWlxU1uU8XWdcjk2bCHkyCnDjd7Ais7ENsAcgzus90YO%2BBtpgnEXsRWWTL9Uv84LcwJGbrBMPTQkpD42tQBfNjXMQCX%2B5M7nVcIoenmnN%2B8oRCFYK21X3wuc5X6K5sn59mqRzCLFy7nlTxAHOKG9fxjdPcvouSa1MtDJAk3Ue209JEkz353r3DTteOS7jwq9OzHJuGDu0F8%2Fbl0bhrTF%2BQ1%2F4YBuIp0gCLg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221B71F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:27,292 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_30d3bf9e21f9f1d09aa9.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=VJND22QekedbiBj5WE5sUcxNXECadZ30CHGFDUV%2B1JzZmDBuIq4msci5xhLYjV2ZXx0yzr8lK20wfLTZx6gF%2Bck9tqKpsSo2c1ExfTzyYfrCBB9a1%2BB9INad0V%2BzSFkUfmrjHV%2BEEPnDoffs%2F6DS9hcaTjb76BGbLoXX5q3qY5o9j%2FwtjhQb1npqCHvNOF%2FGUu%2FEeEFlFQNtolaOVT3cBZFwdD5LPr9wQ1fXXo%2BWclo9gs43hguWGOzl2FWVTCgEwRMmiiAkayLCPWFYGHJsllpS%2F0a0ZiI%2Fx7Boz6ehGNK2wJxvGMckaXRGYRl6wPTK1415TOfyLeBOAIW45Yzzmg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_30d3bf9e21f9f1d09aa9.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=VJND22QekedbiBj5WE5sUcxNXECadZ30CHGFDUV%2B1JzZmDBuIq4msci5xhLYjV2ZXx0yzr8lK20wfLTZx6gF%2Bck9tqKpsSo2c1ExfTzyYfrCBB9a1%2BB9INad0V%2BzSFkUfmrjHV%2BEEPnDoffs%2F6DS9hcaTjb76BGbLoXX5q3qY5o9j%2FwtjhQb1npqCHvNOF%2FGUu%2FEeEFlFQNtolaOVT3cBZFwdD5LPr9wQ1fXXo%2BWclo9gs43hguWGOzl2FWVTCgEwRMmiiAkayLCPWFYGHJsllpS%2F0a0ZiI%2Fx7Boz6ehGNK2wJxvGMckaXRGYRl6wPTK1415TOfyLeBOAIW45Yzzmg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265222803D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:27,293 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '629870'}
2023-03-07 21:57:27,293 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '630484'}
2023-03-07 21:57:27,293 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:27,293 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:29,277 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:30,317 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:57:30,318 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:57:31,298 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:31,390 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_ddb4b29c59b20d5c56a4.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Up74wXhlcgvelQjsvpQFEjXfNTGP%2FvrWWSrPsI8BSJ8i%2B2rjxtVhGEGEzLZ1DRKgPQEWy5DgXyQ8uopRdIUqd0s4Pi3ReQmvzPHHu3eE53aFalAmguRq6TslVsa7ztEFmPtw4xDCqiUbKyApRsjXp013rzsedhk0PDFNGeKCnrS%2FQGSH9tEwFjgbyXKxp5ClR8Ql%2FnxZYidfKisX%2Bx4kDpy60OJWFO2Yrl298DWNG%2B4pLvef%2FMWfg1RAa4%2BJNaRrciljlgdz0hf3PhL%2B8%2Fp5YX5Y8nAWqtFYONbAa8XrzgWlMbpCDwmc97AodPc2qutaN0RyOv0OZBNucO5VlfbX9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_ddb4b29c59b20d5c56a4.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Up74wXhlcgvelQjsvpQFEjXfNTGP%2FvrWWSrPsI8BSJ8i%2B2rjxtVhGEGEzLZ1DRKgPQEWy5DgXyQ8uopRdIUqd0s4Pi3ReQmvzPHHu3eE53aFalAmguRq6TslVsa7ztEFmPtw4xDCqiUbKyApRsjXp013rzsedhk0PDFNGeKCnrS%2FQGSH9tEwFjgbyXKxp5ClR8Ql%2FnxZYidfKisX%2Bx4kDpy60OJWFO2Yrl298DWNG%2B4pLvef%2FMWfg1RAa4%2BJNaRrciljlgdz0hf3PhL%2B8%2Fp5YX5Y8nAWqtFYONbAa8XrzgWlMbpCDwmc97AodPc2qutaN0RyOv0OZBNucO5VlfbX9Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221C7AF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:31,390 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '241359'}
2023-03-07 21:57:31,390 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:31,530 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_c2b39e1ae8e38500e36b.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=T%2BFpHhktsAz7E%2B94jlB6IPrCOhYGwe1Xcy0HmJz6SxzeVqatVGyoZ6ZMPd2lxUFduVZpiMXz5qC9GgF71dsIIjhLidhUb2M7TD3XZw2qDHGuNWx6D23gWlxU1uU8XWdcjk2bCHkyCnDjd7Ais7ENsAcgzus90YO%2BBtpgnEXsRWWTL9Uv84LcwJGbrBMPTQkpD42tQBfNjXMQCX%2B5M7nVcIoenmnN%2B8oRCFYK21X3wuc5X6K5sn59mqRzCLFy7nlTxAHOKG9fxjdPcvouSa1MtDJAk3Ue209JEkz353r3DTteOS7jwq9OzHJuGDu0F8%2Fbl0bhrTF%2BQ1%2F4YBuIp0gCLg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_c2b39e1ae8e38500e36b.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=T%2BFpHhktsAz7E%2B94jlB6IPrCOhYGwe1Xcy0HmJz6SxzeVqatVGyoZ6ZMPd2lxUFduVZpiMXz5qC9GgF71dsIIjhLidhUb2M7TD3XZw2qDHGuNWx6D23gWlxU1uU8XWdcjk2bCHkyCnDjd7Ais7ENsAcgzus90YO%2BBtpgnEXsRWWTL9Uv84LcwJGbrBMPTQkpD42tQBfNjXMQCX%2B5M7nVcIoenmnN%2B8oRCFYK21X3wuc5X6K5sn59mqRzCLFy7nlTxAHOKG9fxjdPcvouSa1MtDJAk3Ue209JEkz353r3DTteOS7jwq9OzHJuGDu0F8%2Fbl0bhrTF%2BQ1%2F4YBuIp0gCLg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026522267BE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:31,531 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '629870'}
2023-03-07 21:57:31,531 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:31,700 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_a09086ac7fbb3b332fc5.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=cn4m2CZwktpYHxFd8vaH64FCjFj9f8SnXNIgPhJkd1U1SLehyHEODS1n1%2FQwElgIahD0Ta1HXMBYTWkZtlmDDx%2BtiWflWF5TcBFZcKqBVhjlsoJk0Pd%2FUba%2B4ZGR05i%2F8C9kt8lHKkOA1qzpPml2C84%2BbXoaotjfLUqQ7KYanOl5kH9PfdESgAx9wj7uTKEMOvUk5tunlqignVUeiBKE5go%2FykRgXqUTBiB%2FkKKuVIc66D2wFgtdks71OgKnWLHq%2BDIQC7ZqNbSCejro1jijbd64%2F9RQ%2BJQcfQ%2FWSifMz5rrLleyRKqYnFjAk1myjxTpxuazFcxMfxkDFultPDdqSw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_a09086ac7fbb3b332fc5.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=cn4m2CZwktpYHxFd8vaH64FCjFj9f8SnXNIgPhJkd1U1SLehyHEODS1n1%2FQwElgIahD0Ta1HXMBYTWkZtlmDDx%2BtiWflWF5TcBFZcKqBVhjlsoJk0Pd%2FUba%2B4ZGR05i%2F8C9kt8lHKkOA1qzpPml2C84%2BbXoaotjfLUqQ7KYanOl5kH9PfdESgAx9wj7uTKEMOvUk5tunlqignVUeiBKE5go%2FykRgXqUTBiB%2FkKKuVIc66D2wFgtdks71OgKnWLHq%2BDIQC7ZqNbSCejro1jijbd64%2F9RQ%2BJQcfQ%2FWSifMz5rrLleyRKqYnFjAk1myjxTpxuazFcxMfxkDFultPDdqSw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002652226AA30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:31,700 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '256560'}
2023-03-07 21:57:31,700 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:31,777 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_30d3bf9e21f9f1d09aa9.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=VJND22QekedbiBj5WE5sUcxNXECadZ30CHGFDUV%2B1JzZmDBuIq4msci5xhLYjV2ZXx0yzr8lK20wfLTZx6gF%2Bck9tqKpsSo2c1ExfTzyYfrCBB9a1%2BB9INad0V%2BzSFkUfmrjHV%2BEEPnDoffs%2F6DS9hcaTjb76BGbLoXX5q3qY5o9j%2FwtjhQb1npqCHvNOF%2FGUu%2FEeEFlFQNtolaOVT3cBZFwdD5LPr9wQ1fXXo%2BWclo9gs43hguWGOzl2FWVTCgEwRMmiiAkayLCPWFYGHJsllpS%2F0a0ZiI%2Fx7Boz6ehGNK2wJxvGMckaXRGYRl6wPTK1415TOfyLeBOAIW45Yzzmg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_30d3bf9e21f9f1d09aa9.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=VJND22QekedbiBj5WE5sUcxNXECadZ30CHGFDUV%2B1JzZmDBuIq4msci5xhLYjV2ZXx0yzr8lK20wfLTZx6gF%2Bck9tqKpsSo2c1ExfTzyYfrCBB9a1%2BB9INad0V%2BzSFkUfmrjHV%2BEEPnDoffs%2F6DS9hcaTjb76BGbLoXX5q3qY5o9j%2FwtjhQb1npqCHvNOF%2FGUu%2FEeEFlFQNtolaOVT3cBZFwdD5LPr9wQ1fXXo%2BWclo9gs43hguWGOzl2FWVTCgEwRMmiiAkayLCPWFYGHJsllpS%2F0a0ZiI%2Fx7Boz6ehGNK2wJxvGMckaXRGYRl6wPTK1415TOfyLeBOAIW45Yzzmg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221D1A60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:31,777 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '630484'}
2023-03-07 21:57:31,778 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:31,793 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_89e164201c08ac4003fe.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=j9RzS69C8Nqxh8nnyowQW%2F6rZ7Pw03gvQKydvawmeKhqZq7Bv23Dry6nbDd3rgyNBIrha4huYwIllRuIIdxlyOPSCD8qY11lOlyCPDSE%2BG0umKLFWeTxD0cNBosYeECRRtVgjyf13HSMNePPcuKm2HJRT9PlIO3WyxtH%2Fmn9M0yLviqZnR0VhN81UjnL14oq%2BSycvvWdJv7JbD%2Fv45%2BubHjV7p%2BbqkAxbdyAiW6OlPVK9wgxsDDGoQ2sroRMjPtdRKTlVH4SudL6ASM1hIgjqCoKbvSFOMmEcyx%2FKMcnNl%2BXt2TM8n%2BPhd7WYZbkiDcMl0CB6DUelXKLUHDw4mqVPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_89e164201c08ac4003fe.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=j9RzS69C8Nqxh8nnyowQW%2F6rZ7Pw03gvQKydvawmeKhqZq7Bv23Dry6nbDd3rgyNBIrha4huYwIllRuIIdxlyOPSCD8qY11lOlyCPDSE%2BG0umKLFWeTxD0cNBosYeECRRtVgjyf13HSMNePPcuKm2HJRT9PlIO3WyxtH%2Fmn9M0yLviqZnR0VhN81UjnL14oq%2BSycvvWdJv7JbD%2Fv45%2BubHjV7p%2BbqkAxbdyAiW6OlPVK9wgxsDDGoQ2sroRMjPtdRKTlVH4SudL6ASM1hIgjqCoKbvSFOMmEcyx%2FKMcnNl%2BXt2TM8n%2BPhd7WYZbkiDcMl0CB6DUelXKLUHDw4mqVPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221B7C10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:31,794 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '545229'}
2023-03-07 21:57:31,794 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:33,313 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:35,328 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:37,342 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:37,869 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_30d3bf9e21f9f1d09aa9.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=VJND22QekedbiBj5WE5sUcxNXECadZ30CHGFDUV%2B1JzZmDBuIq4msci5xhLYjV2ZXx0yzr8lK20wfLTZx6gF%2Bck9tqKpsSo2c1ExfTzyYfrCBB9a1%2BB9INad0V%2BzSFkUfmrjHV%2BEEPnDoffs%2F6DS9hcaTjb76BGbLoXX5q3qY5o9j%2FwtjhQb1npqCHvNOF%2FGUu%2FEeEFlFQNtolaOVT3cBZFwdD5LPr9wQ1fXXo%2BWclo9gs43hguWGOzl2FWVTCgEwRMmiiAkayLCPWFYGHJsllpS%2F0a0ZiI%2Fx7Boz6ehGNK2wJxvGMckaXRGYRl6wPTK1415TOfyLeBOAIW45Yzzmg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_30d3bf9e21f9f1d09aa9.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=VJND22QekedbiBj5WE5sUcxNXECadZ30CHGFDUV%2B1JzZmDBuIq4msci5xhLYjV2ZXx0yzr8lK20wfLTZx6gF%2Bck9tqKpsSo2c1ExfTzyYfrCBB9a1%2BB9INad0V%2BzSFkUfmrjHV%2BEEPnDoffs%2F6DS9hcaTjb76BGbLoXX5q3qY5o9j%2FwtjhQb1npqCHvNOF%2FGUu%2FEeEFlFQNtolaOVT3cBZFwdD5LPr9wQ1fXXo%2BWclo9gs43hguWGOzl2FWVTCgEwRMmiiAkayLCPWFYGHJsllpS%2F0a0ZiI%2Fx7Boz6ehGNK2wJxvGMckaXRGYRl6wPTK1415TOfyLeBOAIW45Yzzmg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265222674C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:37,869 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '630484'}
2023-03-07 21:57:37,869 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:37,964 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_89e164201c08ac4003fe.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=j9RzS69C8Nqxh8nnyowQW%2F6rZ7Pw03gvQKydvawmeKhqZq7Bv23Dry6nbDd3rgyNBIrha4huYwIllRuIIdxlyOPSCD8qY11lOlyCPDSE%2BG0umKLFWeTxD0cNBosYeECRRtVgjyf13HSMNePPcuKm2HJRT9PlIO3WyxtH%2Fmn9M0yLviqZnR0VhN81UjnL14oq%2BSycvvWdJv7JbD%2Fv45%2BubHjV7p%2BbqkAxbdyAiW6OlPVK9wgxsDDGoQ2sroRMjPtdRKTlVH4SudL6ASM1hIgjqCoKbvSFOMmEcyx%2FKMcnNl%2BXt2TM8n%2BPhd7WYZbkiDcMl0CB6DUelXKLUHDw4mqVPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_89e164201c08ac4003fe.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=j9RzS69C8Nqxh8nnyowQW%2F6rZ7Pw03gvQKydvawmeKhqZq7Bv23Dry6nbDd3rgyNBIrha4huYwIllRuIIdxlyOPSCD8qY11lOlyCPDSE%2BG0umKLFWeTxD0cNBosYeECRRtVgjyf13HSMNePPcuKm2HJRT9PlIO3WyxtH%2Fmn9M0yLviqZnR0VhN81UjnL14oq%2BSycvvWdJv7JbD%2Fv45%2BubHjV7p%2BbqkAxbdyAiW6OlPVK9wgxsDDGoQ2sroRMjPtdRKTlVH4SudL6ASM1hIgjqCoKbvSFOMmEcyx%2FKMcnNl%2BXt2TM8n%2BPhd7WYZbkiDcMl0CB6DUelXKLUHDw4mqVPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026522270BE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:37,964 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '545229'}
2023-03-07 21:57:37,964 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:37,989 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_c2b39e1ae8e38500e36b.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=T%2BFpHhktsAz7E%2B94jlB6IPrCOhYGwe1Xcy0HmJz6SxzeVqatVGyoZ6ZMPd2lxUFduVZpiMXz5qC9GgF71dsIIjhLidhUb2M7TD3XZw2qDHGuNWx6D23gWlxU1uU8XWdcjk2bCHkyCnDjd7Ais7ENsAcgzus90YO%2BBtpgnEXsRWWTL9Uv84LcwJGbrBMPTQkpD42tQBfNjXMQCX%2B5M7nVcIoenmnN%2B8oRCFYK21X3wuc5X6K5sn59mqRzCLFy7nlTxAHOKG9fxjdPcvouSa1MtDJAk3Ue209JEkz353r3DTteOS7jwq9OzHJuGDu0F8%2Fbl0bhrTF%2BQ1%2F4YBuIp0gCLg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_c2b39e1ae8e38500e36b.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=T%2BFpHhktsAz7E%2B94jlB6IPrCOhYGwe1Xcy0HmJz6SxzeVqatVGyoZ6ZMPd2lxUFduVZpiMXz5qC9GgF71dsIIjhLidhUb2M7TD3XZw2qDHGuNWx6D23gWlxU1uU8XWdcjk2bCHkyCnDjd7Ais7ENsAcgzus90YO%2BBtpgnEXsRWWTL9Uv84LcwJGbrBMPTQkpD42tQBfNjXMQCX%2B5M7nVcIoenmnN%2B8oRCFYK21X3wuc5X6K5sn59mqRzCLFy7nlTxAHOKG9fxjdPcvouSa1MtDJAk3Ue209JEkz353r3DTteOS7jwq9OzHJuGDu0F8%2Fbl0bhrTF%2BQ1%2F4YBuIp0gCLg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265222704C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:37,989 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '629870'}
2023-03-07 21:57:37,990 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:38,264 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_a09086ac7fbb3b332fc5.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=cn4m2CZwktpYHxFd8vaH64FCjFj9f8SnXNIgPhJkd1U1SLehyHEODS1n1%2FQwElgIahD0Ta1HXMBYTWkZtlmDDx%2BtiWflWF5TcBFZcKqBVhjlsoJk0Pd%2FUba%2B4ZGR05i%2F8C9kt8lHKkOA1qzpPml2C84%2BbXoaotjfLUqQ7KYanOl5kH9PfdESgAx9wj7uTKEMOvUk5tunlqignVUeiBKE5go%2FykRgXqUTBiB%2FkKKuVIc66D2wFgtdks71OgKnWLHq%2BDIQC7ZqNbSCejro1jijbd64%2F9RQ%2BJQcfQ%2FWSifMz5rrLleyRKqYnFjAk1myjxTpxuazFcxMfxkDFultPDdqSw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_a09086ac7fbb3b332fc5.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=cn4m2CZwktpYHxFd8vaH64FCjFj9f8SnXNIgPhJkd1U1SLehyHEODS1n1%2FQwElgIahD0Ta1HXMBYTWkZtlmDDx%2BtiWflWF5TcBFZcKqBVhjlsoJk0Pd%2FUba%2B4ZGR05i%2F8C9kt8lHKkOA1qzpPml2C84%2BbXoaotjfLUqQ7KYanOl5kH9PfdESgAx9wj7uTKEMOvUk5tunlqignVUeiBKE5go%2FykRgXqUTBiB%2FkKKuVIc66D2wFgtdks71OgKnWLHq%2BDIQC7ZqNbSCejro1jijbd64%2F9RQ%2BJQcfQ%2FWSifMz5rrLleyRKqYnFjAk1myjxTpxuazFcxMfxkDFultPDdqSw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265222861C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:38,265 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '256560'}
2023-03-07 21:57:38,265 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:38,326 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_ddb4b29c59b20d5c56a4.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Up74wXhlcgvelQjsvpQFEjXfNTGP%2FvrWWSrPsI8BSJ8i%2B2rjxtVhGEGEzLZ1DRKgPQEWy5DgXyQ8uopRdIUqd0s4Pi3ReQmvzPHHu3eE53aFalAmguRq6TslVsa7ztEFmPtw4xDCqiUbKyApRsjXp013rzsedhk0PDFNGeKCnrS%2FQGSH9tEwFjgbyXKxp5ClR8Ql%2FnxZYidfKisX%2Bx4kDpy60OJWFO2Yrl298DWNG%2B4pLvef%2FMWfg1RAa4%2BJNaRrciljlgdz0hf3PhL%2B8%2Fp5YX5Y8nAWqtFYONbAa8XrzgWlMbpCDwmc97AodPc2qutaN0RyOv0OZBNucO5VlfbX9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_ddb4b29c59b20d5c56a4.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Up74wXhlcgvelQjsvpQFEjXfNTGP%2FvrWWSrPsI8BSJ8i%2B2rjxtVhGEGEzLZ1DRKgPQEWy5DgXyQ8uopRdIUqd0s4Pi3ReQmvzPHHu3eE53aFalAmguRq6TslVsa7ztEFmPtw4xDCqiUbKyApRsjXp013rzsedhk0PDFNGeKCnrS%2FQGSH9tEwFjgbyXKxp5ClR8Ql%2FnxZYidfKisX%2Bx4kDpy60OJWFO2Yrl298DWNG%2B4pLvef%2FMWfg1RAa4%2BJNaRrciljlgdz0hf3PhL%2B8%2Fp5YX5Y8nAWqtFYONbAa8XrzgWlMbpCDwmc97AodPc2qutaN0RyOv0OZBNucO5VlfbX9Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221A7C70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:38,326 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '241359'}
2023-03-07 21:57:38,327 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:39,355 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:41,372 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:43,382 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:45,395 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:45,765 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:57:45,766 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:57:47,409 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:48,606 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_a09086ac7fbb3b332fc5.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=cn4m2CZwktpYHxFd8vaH64FCjFj9f8SnXNIgPhJkd1U1SLehyHEODS1n1%2FQwElgIahD0Ta1HXMBYTWkZtlmDDx%2BtiWflWF5TcBFZcKqBVhjlsoJk0Pd%2FUba%2B4ZGR05i%2F8C9kt8lHKkOA1qzpPml2C84%2BbXoaotjfLUqQ7KYanOl5kH9PfdESgAx9wj7uTKEMOvUk5tunlqignVUeiBKE5go%2FykRgXqUTBiB%2FkKKuVIc66D2wFgtdks71OgKnWLHq%2BDIQC7ZqNbSCejro1jijbd64%2F9RQ%2BJQcfQ%2FWSifMz5rrLleyRKqYnFjAk1myjxTpxuazFcxMfxkDFultPDdqSw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_a09086ac7fbb3b332fc5.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=cn4m2CZwktpYHxFd8vaH64FCjFj9f8SnXNIgPhJkd1U1SLehyHEODS1n1%2FQwElgIahD0Ta1HXMBYTWkZtlmDDx%2BtiWflWF5TcBFZcKqBVhjlsoJk0Pd%2FUba%2B4ZGR05i%2F8C9kt8lHKkOA1qzpPml2C84%2BbXoaotjfLUqQ7KYanOl5kH9PfdESgAx9wj7uTKEMOvUk5tunlqignVUeiBKE5go%2FykRgXqUTBiB%2FkKKuVIc66D2wFgtdks71OgKnWLHq%2BDIQC7ZqNbSCejro1jijbd64%2F9RQ%2BJQcfQ%2FWSifMz5rrLleyRKqYnFjAk1myjxTpxuazFcxMfxkDFultPDdqSw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002652226A6A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:48,606 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '256560'}
2023-03-07 21:57:48,606 ERROR   Thread-13 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:48,637 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_c2b39e1ae8e38500e36b.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=T%2BFpHhktsAz7E%2B94jlB6IPrCOhYGwe1Xcy0HmJz6SxzeVqatVGyoZ6ZMPd2lxUFduVZpiMXz5qC9GgF71dsIIjhLidhUb2M7TD3XZw2qDHGuNWx6D23gWlxU1uU8XWdcjk2bCHkyCnDjd7Ais7ENsAcgzus90YO%2BBtpgnEXsRWWTL9Uv84LcwJGbrBMPTQkpD42tQBfNjXMQCX%2B5M7nVcIoenmnN%2B8oRCFYK21X3wuc5X6K5sn59mqRzCLFy7nlTxAHOKG9fxjdPcvouSa1MtDJAk3Ue209JEkz353r3DTteOS7jwq9OzHJuGDu0F8%2Fbl0bhrTF%2BQ1%2F4YBuIp0gCLg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_c2b39e1ae8e38500e36b.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=T%2BFpHhktsAz7E%2B94jlB6IPrCOhYGwe1Xcy0HmJz6SxzeVqatVGyoZ6ZMPd2lxUFduVZpiMXz5qC9GgF71dsIIjhLidhUb2M7TD3XZw2qDHGuNWx6D23gWlxU1uU8XWdcjk2bCHkyCnDjd7Ais7ENsAcgzus90YO%2BBtpgnEXsRWWTL9Uv84LcwJGbrBMPTQkpD42tQBfNjXMQCX%2B5M7nVcIoenmnN%2B8oRCFYK21X3wuc5X6K5sn59mqRzCLFy7nlTxAHOKG9fxjdPcvouSa1MtDJAk3Ue209JEkz353r3DTteOS7jwq9OzHJuGDu0F8%2Fbl0bhrTF%2BQ1%2F4YBuIp0gCLg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026522267EB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:48,637 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '629870'}
2023-03-07 21:57:48,637 ERROR   Thread-14 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:49,431 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:49,565 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_89e164201c08ac4003fe.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=j9RzS69C8Nqxh8nnyowQW%2F6rZ7Pw03gvQKydvawmeKhqZq7Bv23Dry6nbDd3rgyNBIrha4huYwIllRuIIdxlyOPSCD8qY11lOlyCPDSE%2BG0umKLFWeTxD0cNBosYeECRRtVgjyf13HSMNePPcuKm2HJRT9PlIO3WyxtH%2Fmn9M0yLviqZnR0VhN81UjnL14oq%2BSycvvWdJv7JbD%2Fv45%2BubHjV7p%2BbqkAxbdyAiW6OlPVK9wgxsDDGoQ2sroRMjPtdRKTlVH4SudL6ASM1hIgjqCoKbvSFOMmEcyx%2FKMcnNl%2BXt2TM8n%2BPhd7WYZbkiDcMl0CB6DUelXKLUHDw4mqVPA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_89e164201c08ac4003fe.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=j9RzS69C8Nqxh8nnyowQW%2F6rZ7Pw03gvQKydvawmeKhqZq7Bv23Dry6nbDd3rgyNBIrha4huYwIllRuIIdxlyOPSCD8qY11lOlyCPDSE%2BG0umKLFWeTxD0cNBosYeECRRtVgjyf13HSMNePPcuKm2HJRT9PlIO3WyxtH%2Fmn9M0yLviqZnR0VhN81UjnL14oq%2BSycvvWdJv7JbD%2Fv45%2BubHjV7p%2BbqkAxbdyAiW6OlPVK9wgxsDDGoQ2sroRMjPtdRKTlVH4SudL6ASM1hIgjqCoKbvSFOMmEcyx%2FKMcnNl%2BXt2TM8n%2BPhd7WYZbkiDcMl0CB6DUelXKLUHDw4mqVPA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265221B7B50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:49,566 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '545229'}
2023-03-07 21:57:49,566 ERROR   Thread-16 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:49,597 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_30d3bf9e21f9f1d09aa9.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=VJND22QekedbiBj5WE5sUcxNXECadZ30CHGFDUV%2B1JzZmDBuIq4msci5xhLYjV2ZXx0yzr8lK20wfLTZx6gF%2Bck9tqKpsSo2c1ExfTzyYfrCBB9a1%2BB9INad0V%2BzSFkUfmrjHV%2BEEPnDoffs%2F6DS9hcaTjb76BGbLoXX5q3qY5o9j%2FwtjhQb1npqCHvNOF%2FGUu%2FEeEFlFQNtolaOVT3cBZFwdD5LPr9wQ1fXXo%2BWclo9gs43hguWGOzl2FWVTCgEwRMmiiAkayLCPWFYGHJsllpS%2F0a0ZiI%2Fx7Boz6ehGNK2wJxvGMckaXRGYRl6wPTK1415TOfyLeBOAIW45Yzzmg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Mosaics_0_30d3bf9e21f9f1d09aa9.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=VJND22QekedbiBj5WE5sUcxNXECadZ30CHGFDUV%2B1JzZmDBuIq4msci5xhLYjV2ZXx0yzr8lK20wfLTZx6gF%2Bck9tqKpsSo2c1ExfTzyYfrCBB9a1%2BB9INad0V%2BzSFkUfmrjHV%2BEEPnDoffs%2F6DS9hcaTjb76BGbLoXX5q3qY5o9j%2FwtjhQb1npqCHvNOF%2FGUu%2FEeEFlFQNtolaOVT3cBZFwdD5LPr9wQ1fXXo%2BWclo9gs43hguWGOzl2FWVTCgEwRMmiiAkayLCPWFYGHJsllpS%2F0a0ZiI%2Fx7Boz6ehGNK2wJxvGMckaXRGYRl6wPTK1415TOfyLeBOAIW45Yzzmg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026522286AF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:49,597 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '630484'}
2023-03-07 21:57:49,597 ERROR   Thread-15 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:50,200 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_ddb4b29c59b20d5c56a4.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Up74wXhlcgvelQjsvpQFEjXfNTGP%2FvrWWSrPsI8BSJ8i%2B2rjxtVhGEGEzLZ1DRKgPQEWy5DgXyQ8uopRdIUqd0s4Pi3ReQmvzPHHu3eE53aFalAmguRq6TslVsa7ztEFmPtw4xDCqiUbKyApRsjXp013rzsedhk0PDFNGeKCnrS%2FQGSH9tEwFjgbyXKxp5ClR8Ql%2FnxZYidfKisX%2Bx4kDpy60OJWFO2Yrl298DWNG%2B4pLvef%2FMWfg1RAa4%2BJNaRrciljlgdz0hf3PhL%2B8%2Fp5YX5Y8nAWqtFYONbAa8XrzgWlMbpCDwmc97AodPc2qutaN0RyOv0OZBNucO5VlfbX9Q%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/xiaoxiaomichong/train/ynqj7ir8/media/images/Labels_0_ddb4b29c59b20d5c56a4.jpg?Expires=1678283841&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Up74wXhlcgvelQjsvpQFEjXfNTGP%2FvrWWSrPsI8BSJ8i%2B2rjxtVhGEGEzLZ1DRKgPQEWy5DgXyQ8uopRdIUqd0s4Pi3ReQmvzPHHu3eE53aFalAmguRq6TslVsa7ztEFmPtw4xDCqiUbKyApRsjXp013rzsedhk0PDFNGeKCnrS%2FQGSH9tEwFjgbyXKxp5ClR8Ql%2FnxZYidfKisX%2Bx4kDpy60OJWFO2Yrl298DWNG%2B4pLvef%2FMWfg1RAa4%2BJNaRrciljlgdz0hf3PhL%2B8%2Fp5YX5Y8nAWqtFYONbAa8XrzgWlMbpCDwmc97AodPc2qutaN0RyOv0OZBNucO5VlfbX9Q%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002652228EFD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2023-03-07 21:57:50,200 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '241359'}
2023-03-07 21:57:50,200 ERROR   Thread-12 :134368 [internal_api.py:upload_file():1644] upload_file response body: 
2023-03-07 21:57:51,441 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:53,453 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:55,474 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:56,455 DEBUG   SenderThread:134368 [sender.py:send():232] send: stats
2023-03-07 21:57:57,492 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:57:59,511 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:58:01,273 DEBUG   HandlerThread:134368 [handler.py:handle_request():141] handle_request: stop_status
2023-03-07 21:58:01,274 DEBUG   SenderThread:134368 [sender.py:send_request():246] send_request: stop_status
2023-03-07 21:58:01,537 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
2023-03-07 21:58:03,564 INFO    Thread-7  :134368 [dir_watcher.py:_on_file_modified():257] file/dir modified: F:\CVPR\yolov5-master\wandb\run-20230307_215255-ynqj7ir8\files\output.log
